"""Fictional dataset for the simulated Instagram world (LOCAL environment).

Every username starts with ``sim.`` so simulated leads can never be mistaken
for real businesses; the LIVE environment refuses to act on them.
"""

from __future__ import annotations

from dataclasses import dataclass, field


@dataclass(frozen=True)
class SiteSpec:
    status: int = 200
    builder: str | None = None
    viewport: bool = True
    booking_widget: bool = False
    https: bool = True


@dataclass(frozen=True)
class AccountSpec:
    username: str
    full_name: str
    niche: str | None
    category: str | None
    area: str | None
    bio: str
    website: str | None = None
    followers: int = 1000
    activity: str = "active"  # active | semi | inactive | none
    is_business: bool = True
    is_private: bool = False
    accepts_messages: bool = True
    one_request_limit: bool = False  # IG shows "can't send more until accepted"
    site: SiteSpec | None = None
    reply: tuple[str, float] | None = None  # (text, hours after our first message)
    hashtags: tuple[str, ...] = ()
    email: str | None = None
    phone: str | None = None
    prior_human_thread: bool = False
    extra: dict[str, str] = field(default_factory=dict)


ACCOUNTS: tuple[AccountSpec, ...] = (
    AccountSpec(
        "sim.smileline.dental",
        "Smileline Dental Studio",
        "dental",
        "Dentist",
        "andheri",
        "Family & cosmetic dentistry in Andheri West 🦷 Braces • Implants • Whitening | DM to book your appointment",
        None,
        2400,
        reply=("Hi Rohit, yes interested! What would something like this cost?", 5),
        hashtags=("mumbaidentist", "andheridentist", "smiledesign"),
    ),
    AccountSpec(
        "sim.brightbite.clinic",
        "BrightBite Dental Clinic",
        "dental",
        "Dentist",
        "thane",
        "Painless dental care in Thane West. Call 90000 00011 for appointments",
        "brightbite.wixsite.com/home",
        1800,
        phone="9000000011",
        site=SiteSpec(builder="Wix", booking_widget=False),
        hashtags=("thanedentist", "dentalcare"),
    ),
    AccountSpec(
        "sim.dr.mehta.dental",
        "Dr. Mehta's Dental Care",
        "dental",
        "Dentist",
        "vashi",
        "Root canal & implant specialist | Vashi, Navi Mumbai | WhatsApp for appointments",
        "wa.me/919000000012",
        950,
        activity="semi",
        hashtags=("navimumbaidentist",),
    ),
    AccountSpec(
        "sim.pearl.dental.bandra",
        "Pearl Dental Bandra",
        "dental",
        "Dentist",
        "bandra",
        "Modern dentistry in Bandra West. Book online below",
        "https://pearldental.example",
        5200,
        site=SiteSpec(booking_widget=True),
        hashtags=("mumbaidentist", "bandra"),
    ),
    AccountSpec(
        "sim.pearl.dental.khar",
        "Pearl Dental Khar",
        "dental",
        "Dentist",
        "khar",
        "Pearl Dental's Khar branch. Book online below",
        "https://pearldental.example",
        1300,
        site=SiteSpec(booking_widget=True),
        hashtags=("mumbaidentist",),
    ),
    AccountSpec(
        "sim.glowup.salon.powai",
        "GlowUp Unisex Salon",
        "salon",
        "Hair Salon",
        "powai",
        "Hair • Skin • Nails | Powai | DM for appointments 💇",
        "linktr.ee/glowuppowai",
        3100,
        reply=("Please stop messaging me", 3),
        hashtags=("powaisalon", "mumbaisalon"),
    ),
    AccountSpec(
        "sim.tresses.by.nisha",
        "Tresses by Nisha",
        "salon",
        "Hair Salon",
        "borivali",
        "Bridal hair & makeup artist in Borivali. Bookings via WhatsApp 9000000013",
        None,
        8900,
        phone="9000000013",
        hashtags=("mumbaibridal", "borivali", "mumbaisalon"),
    ),
    AccountSpec(
        "sim.urban.fade.barbers",
        "Urban Fade Barbers",
        "salon",
        "Barber Shop",
        "dadar",
        "Classic cuts & beard grooming | Dadar West | Walk-ins welcome",
        "urbanfade.example",
        1200,
        site=SiteSpec(status=404),
        hashtags=("mumbaibarber",),
    ),
    AccountSpec(
        "sim.the.brew.room",
        "The Brew Room",
        "cafe",
        "Cafe",
        "thane",
        "Specialty coffee & all-day breakfast in Thane ☕ Reservations: DM us",
        None,
        6400,
        reply=("Can you share some examples of sites you've built?", 8),
        hashtags=("thanecafe", "mumbaicafe", "specialtycoffee"),
    ),
    AccountSpec(
        "sim.masala.junction",
        "Masala Junction",
        "restaurant",
        "Indian Restaurant",
        "kharghar",
        "North Indian & Mughlai | Kharghar, Navi Mumbai | Order on Zomato",
        "zomato.com/mumbai/masala-junction",
        2200,
        hashtags=("navimumbaifood", "kharghar"),
    ),
    AccountSpec(
        "sim.bombay.bao",
        "Bombay Bao House",
        "restaurant",
        "Restaurant",
        "lower parel",
        "Asian street food. Lower Parel. Reservations via link",
        "https://bombaybao.example",
        9400,
        site=SiteSpec(builder="WordPress"),
        hashtags=("mumbaifood", "lowerparel"),
    ),
    AccountSpec(
        "sim.juhu.beach.bites",
        "Juhu Beach Bites",
        "restaurant",
        "Restaurant",
        "juhu",
        "Iconic beach cafe in Juhu",
        "https://juhubeachbites.example",
        180_000,
        site=SiteSpec(booking_widget=True),
        hashtags=("mumbaifood", "juhu"),
    ),
    AccountSpec(
        "sim.mega.burger.india",
        "MegaBurger India",
        "restaurant",
        "Fast Food Restaurant",
        "mumbai",
        "Burgers across India 🍔",
        "https://megaburger.example",
        450_000,
        hashtags=("mumbaifood",),
    ),
    AccountSpec(
        "sim.pawsome.pets.andheri",
        "Pawsome Pet Store",
        "pet",
        "Pet Store",
        "andheri",
        "Pet food, toys & grooming | Andheri East | Call/WhatsApp 9000000014",
        None,
        1400,
        phone="9000000014",
        hashtags=("mumbaipets", "petshopmumbai"),
    ),
    AccountSpec(
        "sim.happy.tails.grooming",
        "Happy Tails Grooming",
        "pet",
        "Pet Groomer",
        "nerul",
        "Home grooming across Navi Mumbai 🐶 DM to book a slot",
        "happytails.carrd.co",
        760,
        site=SiteSpec(builder="Carrd"),
        hashtags=("navimumbaipets", "petshopmumbai"),
    ),
    AccountSpec(
        "sim.zari.boutique",
        "Zari Boutique",
        "boutique",
        "Boutique Store",
        "malad",
        "Designer ethnic wear & bridal lehengas | Malad West | DM for orders",
        "instamojo.com/zari",
        4300,
        hashtags=("mumbaiboutique", "bridallehenga"),
    ),
    AccountSpec(
        "sim.threads.of.thane",
        "Threads of Thane",
        "boutique",
        "Clothing Store",
        "thane",
        "Handloom sarees | Thane | WhatsApp 9000000015",
        None,
        650,
        activity="inactive",
        phone="9000000015",
        hashtags=("thaneboutique",),
    ),
    AccountSpec(
        "sim.serenity.spa.juhu",
        "Serenity Day Spa",
        "spa",
        "Spa",
        "juhu",
        "Ayurvedic massages & wellness in Juhu. Call to book",
        "http://serenityspa.example",
        2900,
        site=SiteSpec(viewport=False, https=False),
        hashtags=("mumbaispa",),
    ),
    AccountSpec(
        "sim.skinsense.derma",
        "SkinSense Dermatology",
        "clinic",
        "Dermatologist",
        "chembur",
        "Skin & hair clinic in Chembur | Book via Practo",
        "practo.com/mumbai/clinic/skinsense",
        3700,
        hashtags=("mumbaiskincare",),
    ),
    AccountSpec(
        "sim.corefit.studio",
        "CoreFit Studio",
        "fitness",
        "Gym",
        "ghatkopar",
        "Functional training & yoga | Ghatkopar East | DM for a trial class",
        None,
        5100,
        one_request_limit=True,
        hashtags=("mumbaifitness", "ghatkopar"),
    ),
    AccountSpec(
        "sim.pixelcraft.webstudio",
        "PixelCraft Web Studio",
        None,
        "Web Designer",
        "andheri",
        "Website design & digital marketing agency in Mumbai",
        "https://pixelcraft.example",
        2100,
        site=SiteSpec(),
        hashtags=("mumbaiwebdesign",),
    ),
    AccountSpec(
        "sim.priya.travels",
        "Priya S",
        None,
        None,
        "mumbai",
        "Wanderlust ✈️ | Mumbai girl | Coffee addict",
        None,
        890,
        is_business=False,
        hashtags=("mumbaicafe",),
    ),
    AccountSpec(
        "sim.nailart.by.riya",
        "Nail Art by Riya",
        "salon",
        "Nail Salon",
        "vashi",
        "Nail extensions in Vashi | DM to book",
        None,
        1900,
        is_private=True,
    ),
    AccountSpec(
        "sim.tiny.bakes.dadar",
        "Tiny Bakes",
        "cafe",
        "Bakery",
        "dadar",
        "Homemade cupcakes | Dadar | DM to order",
        None,
        60,
        hashtags=("mumbaibakery",),
    ),
    AccountSpec(
        "sim.cake.canvas.powai",
        "Cake Canvas",
        "cafe",
        "Bakery",
        "powai",
        "Custom cakes in Powai 🎂 DM to order",
        None,
        2600,
        accepts_messages=False,
        hashtags=("mumbaibakery", "powai"),
    ),
    AccountSpec(
        "sim.aroma.kitchen.mulund",
        "Aroma Kitchen",
        "restaurant",
        "Restaurant",
        "mulund",
        "Home-style thalis in Mulund | Call 9000000016",
        None,
        1100,
        phone="9000000016",
        reply=("Not interested, thanks", 20),
        hashtags=("mumbaifood", "mulund"),
    ),
    AccountSpec(
        "sim.lotus.physio",
        "Lotus Physiotherapy",
        "clinic",
        "Physical Therapist",
        "kandivali",
        "Sports & post-op physio in Kandivali West. WhatsApp for appointments",
        "lotusphysio.business.site",
        900,
        site=SiteSpec(status=404),
        hashtags=("mumbaiphysio",),
    ),
    AccountSpec(
        "sim.inkwell.tattoo",
        "Inkwell Tattoo Studio",
        "studio",
        "Tattoo & Piercing Shop",
        "bandra",
        "Custom tattoos by appointment | Bandra | DM to book",
        "linktr.ee/inkwelltattoo",
        7200,
        hashtags=("mumbaitattoo", "bandra"),
    ),
    AccountSpec(
        "sim.goldleaf.jewels",
        "Goldleaf Jewellers",
        "jewellery",
        "Jewelry/Watches",
        "borivali",
        "Since 1985. Gold & diamond jewellery in Borivali",
        "https://goldleafjewels.example",
        3300,
        activity="semi",
        site=SiteSpec(builder="Shopify"),
        hashtags=("mumbaijewellery",),
    ),
    AccountSpec(
        "sim.fit.with.aman",
        "Aman | Personal Trainer",
        "fitness",
        "Personal Trainer",
        "worli",
        "Online & in-person coaching in Worli. Book a call below",
        "calendly.com/aman-fit",
        12_000,
        hashtags=("mumbaifitness",),
    ),
    AccountSpec(
        "sim.chai.and.chapters",
        "Chai & Chapters",
        "cafe",
        "Cafe",
        "vile parle",
        "Bookstore cafe in Vile Parle | Events every weekend | DM for table bookings",
        None,
        4100,
        prior_human_thread=True,
        hashtags=("mumbaicafe", "vileparle"),
    ),
)

CAPTION_THEMES: dict[str, tuple[str, ...]] = {
    "dental": (
        "Smile makeover for a happy patient",
        "Invisible aligners explained",
        "Teeth whitening results",
        "Meet our team of dentists",
        "Dental implants FAQ",
    ),
    "salon": (
        "Balayage transformation",
        "Bridal hair trial",
        "Keratin treatment results",
        "Fresh fade for the weekend",
        "Nail art of the week",
    ),
    "cafe": (
        "Our new cold brew is here",
        "Weekend brunch spread",
        "Latte art Sunday",
        "Fresh bakes this morning",
        "Book club evening recap",
    ),
    "restaurant": (
        "Chef's special thali",
        "Butter chicken night",
        "New bao menu launch",
        "Weekend buffet spread",
        "Behind the scenes in our kitchen",
    ),
    "pet": (
        "Grooming day for Bruno",
        "New dog food range in store",
        "Cat toys restocked",
        "Puppy spa session",
        "Adoption drive this Sunday",
    ),
    "boutique": (
        "New bridal lehenga collection",
        "Handloom saree drape",
        "Festive wear preview",
        "Custom blouse designs",
        "Behind the scenes at our studio",
    ),
    "spa": (
        "Ayurvedic abhyanga massage",
        "Couples spa day",
        "Wellness retreat weekend",
        "Aromatherapy session",
        "Monsoon skin care",
    ),
    "clinic": (
        "Post-op rehab success story",
        "Skin care routine tips",
        "Knee pain exercises",
        "Acne treatment results",
        "Meet our physiotherapist",
    ),
    "fitness": (
        "Morning HIIT class",
        "Yoga for beginners",
        "Member transformation",
        "Functional training circuit",
        "Trial class this Saturday",
    ),
    "studio": (
        "Fine line floral tattoo",
        "Custom sleeve in progress",
        "Flash day this weekend",
        "Healed tattoo showcase",
        "Studio tour",
    ),
    "jewellery": (
        "Diamond solitaire collection",
        "Temple jewellery for weddings",
        "Gold bangles",
        "Custom engagement rings",
        "Festive collection launch",
    ),
}

# Seeds referenced by the network-based discovery strategies in local mode.
FOLLOWER_POOL: tuple[str, ...] = (
    "sim.priya.travels",
    "sim.tiny.bakes.dadar",
    "sim.cake.canvas.powai",
    "sim.the.brew.room",
    "sim.corefit.studio",
    "sim.deleted.account",
)
